# do_my_job:
#   every: 30s
#   class: Jobs::SleepJob
#   args: 1
#   description: Runs the perform method in MyJob

update_activities_status:
  cron: "*/1 * * * * "
  # every: 30s
  class: Jobs::UpdateActivityJob
  description: update_activities_status 